"""Displayed keys for the pinned Classic 0.47.05 binding-file profile.

This lists physical-key labels only, never mappings to menu-specific actions.
The runtime parser derives each complete native event set from the hash-bound file.
"""

BINDING_PROFILE = "native_keyboard_bindings/v1"
BINDINGS_SHA256 = "8176d2bd7a8d96f6bb12feb654519a8361a6f262363b84ec48963be832cb7efd"
# Legacy KEY records are byte-code-like values, not general Unicode text input.
CHARACTER_KEYS = frozenset(chr(value) for value in range(32, 256) if value != 127)
SYMBOL_KEYS = frozenset(
    {
        "SYM:0:1",
        "SYM:0:2",
        "SYM:0:3",
        "SYM:0:4",
        "SYM:0:5",
        "SYM:0:6",
        "SYM:0:7",
        "SYM:0:8",
        "SYM:0:9",
        "SYM:0:Backspace",
        "SYM:0:Down",
        "SYM:0:ESC",
        "SYM:0:Enter",
        "SYM:0:F1",
        "SYM:0:F10",
        "SYM:0:F11",
        "SYM:0:F12",
        "SYM:0:F2",
        "SYM:0:F3",
        "SYM:0:F4",
        "SYM:0:F5",
        "SYM:0:F6",
        "SYM:0:F7",
        "SYM:0:F8",
        "SYM:0:F9",
        "SYM:0:Left",
        "SYM:0:Numpad 1",
        "SYM:0:Numpad 2",
        "SYM:0:Numpad 3",
        "SYM:0:Numpad 4",
        "SYM:0:Numpad 5",
        "SYM:0:Numpad 6",
        "SYM:0:Numpad 7",
        "SYM:0:Numpad 8",
        "SYM:0:Numpad 9",
        "SYM:0:Numpad Enter",
        "SYM:0:Page Down",
        "SYM:0:Page Up",
        "SYM:0:Right",
        "SYM:0:Space",
        "SYM:0:Tab",
        "SYM:0:Up",
        "SYM:1:1",
        "SYM:1:2",
        "SYM:1:3",
        "SYM:1:4",
        "SYM:1:5",
        "SYM:1:6",
        "SYM:1:7",
        "SYM:1:8",
        "SYM:1:9",
        "SYM:1:Down",
        "SYM:1:ESC",
        "SYM:1:Enter",
        "SYM:1:F1",
        "SYM:1:F2",
        "SYM:1:F3",
        "SYM:1:F4",
        "SYM:1:F5",
        "SYM:1:F6",
        "SYM:1:F7",
        "SYM:1:F8",
        "SYM:1:Left",
        "SYM:1:Numpad 1",
        "SYM:1:Numpad 2",
        "SYM:1:Numpad 3",
        "SYM:1:Numpad 4",
        "SYM:1:Numpad 5",
        "SYM:1:Numpad 6",
        "SYM:1:Numpad 7",
        "SYM:1:Numpad 8",
        "SYM:1:Numpad 9",
        "SYM:1:Numpad Enter",
        "SYM:1:Page Down",
        "SYM:1:Page Up",
        "SYM:1:Right",
        "SYM:1:Space",
        "SYM:1:Tab",
        "SYM:1:Up",
        "SYM:2:1",
        "SYM:2:2",
        "SYM:2:3",
        "SYM:2:4",
        "SYM:2:5",
        "SYM:2:6",
        "SYM:2:7",
        "SYM:2:8",
        "SYM:2:9",
        "SYM:2:Down",
        "SYM:2:F10",
        "SYM:2:Left",
        "SYM:2:Numpad 1",
        "SYM:2:Numpad 2",
        "SYM:2:Numpad 3",
        "SYM:2:Numpad 4",
        "SYM:2:Numpad 5",
        "SYM:2:Numpad 6",
        "SYM:2:Numpad 7",
        "SYM:2:Numpad 8",
        "SYM:2:Numpad 9",
        "SYM:2:Page Down",
        "SYM:2:Page Up",
        "SYM:2:Right",
        "SYM:2:Up",
        "SYM:2:a",
        "SYM:2:b",
        "SYM:2:c",
        "SYM:2:d",
        "SYM:2:e",
        "SYM:2:f",
        "SYM:2:g",
        "SYM:2:h",
        "SYM:2:i",
        "SYM:2:j",
        "SYM:2:k",
        "SYM:2:l",
        "SYM:2:m",
        "SYM:2:n",
        "SYM:2:o",
        "SYM:2:p",
        "SYM:2:q",
        "SYM:2:r",
        "SYM:2:s",
        "SYM:2:t",
        "SYM:2:u",
        "SYM:2:v",
        "SYM:2:w",
        "SYM:2:x",
        "SYM:2:y",
        "SYM:2:z",
        "SYM:4:1",
        "SYM:4:2",
        "SYM:4:3",
        "SYM:4:4",
        "SYM:4:5",
        "SYM:4:6",
        "SYM:4:7",
        "SYM:4:8",
        "SYM:4:9",
        "SYM:4:Down",
        "SYM:4:Equals",
        "SYM:4:Left",
        "SYM:4:Minus",
        "SYM:4:Numpad 1",
        "SYM:4:Numpad 2",
        "SYM:4:Numpad 3",
        "SYM:4:Numpad 4",
        "SYM:4:Numpad 5",
        "SYM:4:Numpad 6",
        "SYM:4:Numpad 7",
        "SYM:4:Numpad 8",
        "SYM:4:Numpad 9",
        "SYM:4:Page Down",
        "SYM:4:Page Up",
        "SYM:4:Right",
        "SYM:4:Up",
        "SYM:4:a",
        "SYM:4:b",
        "SYM:4:c",
        "SYM:4:d",
        "SYM:4:e",
        "SYM:4:f",
        "SYM:4:g",
        "SYM:4:h",
        "SYM:4:i",
        "SYM:4:j",
        "SYM:4:k",
        "SYM:4:l",
        "SYM:4:m",
        "SYM:4:n",
        "SYM:4:o",
        "SYM:4:p",
        "SYM:4:q",
        "SYM:4:r",
        "SYM:4:s",
        "SYM:4:t",
        "SYM:4:u",
        "SYM:4:v",
        "SYM:4:w",
        "SYM:4:x",
        "SYM:4:y",
        "SYM:4:z",
    }
)
DISPLAY_KEYS = CHARACTER_KEYS | SYMBOL_KEYS


def binding_event(key: str) -> dict:
    if key not in DISPLAY_KEYS:
        raise ValueError("Keyboard keys must be supported native interface events")
    if key in CHARACTER_KEYS:
        return {"type": "character", "value": key}
    _, mask, name = key.split(":", 2)
    return {"type": "symbol", "value": name, "modifiers": int(mask)}
