---
# Repository and install paths
fortgym_repo_url: "https://github.com/lemoz/fort-gym.git"
fortgym_checkout_ref: "main"
fortgym_install_dir: "/opt/fort-gym"
fortgym_venv_dir: "{{ fortgym_install_dir }}/.venv"
fortgym_env_path: "/etc/fort-gym.env"
fortgym_service_enabled: false
fortgym_service_port: 8000


fortgym_python_executable: "/usr/bin/python3.11"
# DFHack distribution (set to a valid tarball/zip URL during deployment)
dwarf_fortress_archive_url: "http://www.bay12games.com/dwarves/df_50_12_linux.tar.bz2"
dfhack_archive_url: "https://github.com/DFHack/dfhack/releases/download/50.12-r1/dfhack-50.12-r1-Linux-64bit.tar.bz2"
dfhack_archive_checksum: ""
dfhack_install_dir: "/opt/dwarf-fortress"
dfhack_env_path: "/etc/dfhack.env"
dfhack_remote_port: 5000
dfhack_service_enabled: true

dfhack_display: ":99"

# System accounts
service_user: "dfh"
service_group: "dfh"

# Allowed TCP ports through UFW
allow_tcp_ports:
  - 22
  - 5000
  - 8000

# Base packages required by fort-gym + DFHack
base_packages:
  - xvfb
  - xauth
  - x11-xserver-utils
  - fonts-dejavu-core
  - libglu1-mesa
  - libxrender1
  - libxi6
  - libxrandr2
  - libxcursor1
  - libsdl1.2debian
  - libslang2
  - libcaca0
  - libsdl-ttf2.0-0
  - libsdl-image1.2
  - libgtk2.0-0
  - unzip
  - curl
  - ca-certificates
  - jq
  - git
  - python3
  - python3-venv
  - python3.11
  - python3.11-venv
  - python3-pip
  - ufw
